myapp/config/routes.rb
Rails.application.routes.draw do
  resources :virtual_runs
  resources :leafs
  resources :stamps do
    collection do
      get 'statistics'
    end
  end
  resources :modelstocks
  resources :books
  devise_for :users
  resources :groups
  resources :providers
  resources :authors


  root 'authors#index'
  get 'index' => 'authors#index'








end

myapp/app/models/leaf.rb
#coding: utf-8
class Leaf < ActiveRecord::Base
  has_many :stamps

  # application id
  APP_ID=4

  # constants
  GROUP1 = [
    '(none)',
    '日本', '琉球',
    'GB', 'England', 'Northern Ireland', 'Scotland', 'Wales',
    'Isle of Man', 'Guernsey', 'Jersey',
    'その他'
  ]

  GROUP2 = [
    '(none)',
    '普通切手', '記念切手', '年賀切手', 'シート',
    'Definitive', 'Commemorative', 'Miniature Sheet',
    'その他'
  ]

  SHORTER_NAME = {
    'Definitive' => 'Def.',
    'Commemorative' => 'Comm.',
    'Miniature Sheet' => 'MS'
  }


  # validation
  validates_presence_of :title, :group1, :group2
  validates_length_of :title, :group1, :group2, in: 1..255
  validates_inclusion_of :group1, within: GROUP1
  validates_inclusion_of :group2, within: GROUP2

  def self.group1_list
    GROUP1
  end

  def self.group2_list
    GROUP2
  end

  def self.shorter_name
    SHORTER_NAME
  end

end

myapp/app/controllers/leafs_controller.rb
#coding: utf-8
class LeafsController < ApplicationController
  before_action :set_leaf, only: [:show, :edit, :update, :destroy]

  # GET /leafs
  def index
    if params[:select].present? then
      sel = params[:select]
    elsif session[:select].present? then
      sel = session[:select]
    else
      sel = ''
    end

    case sel
    when 'ALL' then
      @leafs = Leaf.all
      session[:select] = 'ALL'
    when 'CLEAR' then
      @leafs = nil
      session[:select] = ''
    when '' then
      @leafs = Leaf.all
      session[:select] = ''
    else
      @leafs = Leaf.select(:id, :group2, :title).where('group1 = ?', sel).order(group2: :asc, title: :asc)
      session[:select] = sel
    end

  end

  # GET /leafs/1
  def show
    @leaf.group3 = '(' + @leaf.group3 + ')' if (@leaf.group3.present? && @leaf.group3 != '(none)')
  end

  # GET /leafs/new
  def new
    @leaf = Leaf.new
    render_new
  end

  # GET /leafs/1/edit
  def edit
    render_edit
  end

  # POST /leafs
  def create
    @leaf = Leaf.new(leaf_params)

    if @leaf.save
      redirect_to @leaf, notice: t('message.registered')
    else
      render_new
    end
  end

  # PATCH/PUT /leafs/1
  def update
    if @leaf.update(leaf_params)
      redirect_to @leaf, notice: t('message.updated')
    else
      render_edit
    end
  end

  # DELETE /leafs/1
  def destroy
    @leaf.destroy
    redirect_to leafs_url, notice: t('message.deleted')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leaf
      @leaf = Leaf.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def leaf_params
      params.require(:leaf).permit(:title, :subtitle, :description, :group1, :group2, :group3)
    end
end

myapp/app/helpers/leafs_helper.rb
module LeafsHelper

  def leaf_group1_selection
    list = []
    Leaf.group1_list.each do |lf|
        list << [lf, lf]
    end
    return list
  end

  def leaf_group2_selection
    list = []
    Leaf.group2_list.each do |lf|
        list << [lf, lf]
    end
    return list
  end

  def leaf_title(t, s)
    if s.present? then
      return t + '>>' + s
    else
      return t
    end
  end

  def leaf_image(s)
    if s.purchased? && s.image_path.present? && File.exist?(Stamp.image_path_base + s.image_path) then
      return s.image_path
    elsif s.not_purchased? then
      return Stamp.not_purchase_image
    end
    return Stamp.no_image
  end
end

myapp/app/views/leafs/_form.html.erb
<div class="form_layout">

<%= form_for(@leaf) do |f| %>

<%= render partial: '/parts/form_errors', locals: {obj: @leaf} %>

<div>
<fieldset>
  <%= f.label t('leaf.title') %><br>
  <%= f.text_field :title %><br>
  <%= f.label t('leaf.subtitle') %><br>
  <%= f.text_field :subtitle %><br>
  <%= f.label t('leaf.group1') %><br>
  <%= f.select :group1, options_for_select(leaf_group1_selection, @leaf.group1) %><br>
  <%= f.label t('leaf.group2') %><br>
  <%= f.select :group2, options_for_select(leaf_group2_selection, @leaf.group2) %><br>
  <%= f.label t('leaf.group3') %><br>
  <%= f.text_field :group3 %><br>
</fieldset>
</div>

<div>
<fieldset>
  <%= f.label t('leaf.description') %><br>
  <%= f.text_area :description %><br>
  <%= f.submit val, {:class => "actions"} %>
</fieldset>
</div>

<% end %>

</div>

myapp/app/views/leafs/_index_group1.html.erb
<% Leaf.group1_list.each do |g| %>
  <% if g != '(none)' then %>
  <div class="leaf">
    <%= link_to g, leafs_path(:select => g) %>
  </div>
  <% end %>
<% end %>
  <div class="index_layout_all">
    <%= link_to t('leaf.all'), leafs_path(:select => 'ALL') %>
  </div>
  <div class="index_layout_ctl">
    <%= link_to t('common.new'), new_leaf_path %>
  </div>

myapp/app/views/leafs/_index_leaf.html.erb
<% @leafs.each do |leaf| %>
  <div class="leaf">
    <%= link_to leaf do %>
      <p><%= ss(leaf.group2) %></p>
      <p><%= ss(leaf.title) %></p>
    <% end %>
  </div>
<% end %>
  <div class="index_layout_ctl">
    <%= link_to t('common.back'), leafs_path(:select => 'CLEAR') %>
  </div>

myapp/app/views/leafs/_show_footer.html.erb
<div id="leaf_layout_footer">
  <textarea disabled><%= val.description %></textarea>
</div>

myapp/app/views/leafs/_show_header.html.erb
<div id="leaf_layout_header">
  <h2><%= val.title %></h2>
  <h3><%= val.subtitle %></h3>
  <h4><%= val.group2 %></h4>
  <% if val.group3 != '(none)' then %>
    <h4><%= val.group3 %></h4>
  <% end %>
</div>

myapp/app/views/leafs/_show_stamps.html.erb
<!-- <div id="leaf_layout_stamps"> -->
<div id="leaf_layout_stamps" class="js-masonry" data-masonry-options='{"columnWidth": 100,"gutter": 10,"isFitWidth": true,"itemSelector": ".stamp"}'>
  <% val.stamps.each do |stamp| %>
  <div class="stamp">
    <%= link_to image_tag(leaf_image(stamp), {:size => "100x100"}), stamp_path(stamp.id) %>
    <p><%= stamp.name + ' '+ stamp.price %></p>
  </div>
  <% end %>
</div>

myapp/app/views/leafs/index.html.erb

<% title = leaf_title(t('common.leafs'), session[:select]) %>
<%= render partial: '/parts/title', locals: {val: title} %>

<!-- <div class="index_layout"> -->
<div class="js-masonry" data-masonry-options='{"columnWidth": 5,"itemSelector": ".leaf, .index_layout_all, .index_layout_ctl"}'>

<% if session[:select].present? then %>

  <%= render partial: 'index_leaf' %>

<% else %>

  <%= render partial: 'index_group1' %>

<% end %>

</div>

myapp/app/views/leafs/show.html.erb

<% title = leaf_title(t('common.show'), session[:select]) %>
<%= render partial: '/parts/title', locals: {val: title} %>

<div id="operations">
  <%= render partial: '/parts/commands', locals: {command: 'show', obj: @leaf } %>
</div>

<div id="leaf_layout">
  <%= render partial: 'show_header', locals: {val: @leaf} %>
  <%= render partial: 'show_stamps', locals: {val: @leaf} %>
  <%= render partial: 'show_footer', locals: {val: @leaf} %>
</div>