myapp/config/routes.rb
Rails.application.routes.draw do
  resources :virtual_runs
  resources :leafs
  resources :stamps do
    collection do
      get 'statistics'
    end
  end
  resources :modelstocks
  resources :books
  devise_for :users
  resources :groups
  resources :providers
  resources :authors


  root 'authors#index'
  get 'index' => 'authors#index'








end

myapp/app/models/stamp.rb
#coding: utf-8
class Stamp < ActiveRecord::Base
  belongs_to :leaf

  # application id
  APP_ID=3

  # constants
  IMAGE_PATH_BASE = "#{Rails.root}/app/assets/images/"

  NO_IMAGE = 'no_image.png'
  NOT_PURCHASE_IMAGE = 'not_purchase.png'

  IMAGE_SIZE = '100x100'

  ICONS = {
    '__purchased__' => 'icons/tick.png',
    '__plan__' => 'icons/key.png',
    '__not_purchase__' => 'icons/cross.png',
    'edit' => 'icons/application_edit.png'
  }

  AREAS = [
    '(none)',
    'JP', 'Ryukyu',
    'GB', 'England', 'Northern Ireland', 'Scotland', 'Wales', 'Isle of Man', 'Guernsey', 'Jersey'
  ]

  STATUSES = ['__not_purchase__', '__purchased__', '__plan__' ]

  GROUP1 = [
   '(none)',
   '切手趣味週間', '国際文通週間', '年賀切手', '第一次国立公園', '第二次国立公園',
   '国定公園', '普通切手', '記念切手', '切手シート',
   'Definitive', 'Commemorative', 'Sheet'
  ]

  # validation
  validates_presence_of :name, :area, :status, :group1
  validates_length_of :name, :issue_date, :image_path, in: 1..255
  validates_length_of :remark1, :remark2, :remark3, in: 1..255
  validates_length_of :group1, :group2, :group3, :price, :area, :status, in: 1..255
  validates_inclusion_of :area, within: AREAS
  validates_inclusion_of :status, within: STATUSES
  validates_inclusion_of :group1, within: GROUP1

  def self.image_path_base
    IMAGE_PATH_BASE
  end

  def self.no_image
    NO_IMAGE
  end

  def self.not_purchase_image
    NOT_PURCHASE_IMAGE
  end

  def self.image_size
    IMAGE_SIZE
  end

  def self.icons
    ICONS
  end

  def self.area_list
    AREAS
  end

  def self.status_list
    STATUSES
  end

  def self.group1_list
    GROUP1
  end

  def purchased?
    if self.status == Stamp.status_list[1] then
      return true
    end
    return false      
  end

  def planned?
    if self.status == Stamp.status_list[2] then
      return true
    end
    return false
  end

  def not_purchased?
    if self.status == Stamp.status_list[0] then
      return true
    end
    return false
  end

end

myapp/app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :set_stamp, only: [:show, :edit, :update, :destroy]

  # GET /stamps
  def index

    # ORDER BY parameter
    if params[:order].present? then
      order = params[:order]
    elsif session[:order].present? then
      order = session[:order]
    else 
      order = 'name' # default
    end
    session[:order] = order # store order

    # LIKE parameter
    if params[:keyword].present? && params[:commit].present? && params[:commit] == t('common.search') then
      like = '%' + params[:keyword].to_s + '%'
      session[:keyword] = params[:keyword].to_s
    elsif session[:keyword].present? then
      like = '%' + session[:keyword].to_s + '%'
    else
      like = ''
      session[:keyword] = ''
      session[:order] = ''
    end

    # all clear
    if params[:commit].present? && params[:commit] == t('common.clear') then
      like = ''
      session[:keyword] = ''
      session[:order] = ''
    end

    # exec SELECT
    select = 'id, name, area, group1, group2, group3, issue_date, price, remark1, remark2, remark3, leaf_id, status'
    @stamps = Stamp.select(select)
    if like.present? then
      @stamps = @stamps.where('(name LIKE ?) OR (area LIKE ?) OR (status LIKE ?) OR (group1 LIKE ?) OR (group2 LIKE ?) OR (group3 LIKE ?) OR (remark1 LIKE ?) OR (remark2 LIKE ?) OR (remark3 LIKE ?)', like, like , like, like, like, like, like, like, like)
    end
    @stamps = @stamps.order(order).page(params[:page])

  end

  # GET /stamps/1
  def show
  end

  # GET /stamps/new
  def new
    @stamp = Stamp.new
    render_new
  end

  # GET /stamps/1/edit
  def edit
    render_edit
  end

  # POST /stamps
  def create
    @stamp = Stamp.new(stamp_params)

    if @stamp.save
      redirect_to @stamp, notice: t('message.registered')
    else
      render_new
    end
  end

  # PATCH/PUT /stamps/1
  def update
    if @stamp.update(stamp_params)
      redirect_to @stamp, notice: t('message.updated')
    else
      render_edit
    end
  end

  # DELETE /stamps/1
  def destroy
    @stamp.destroy
    redirect_to stamps_url, notice: t('message.deleted')
  end

  def statistics
    @data = []
    a = []
    Stamp.all.group(:area).order('count_area desc').count(:area).each do |i|
      a << { "label" => i[0], "value" => i[1] }
    end
    @data[0] = a

    s = []
    Stamp.all.group(:status).order('count_status desc').count(:status).each do |j|
      s << { "label" => t('stamp.statuses.' + j[0]), "value" => j[1] }
    end
    @data[1] = s

    a1 = []
    a2 = []
    Stamp.all.group(:area, :status).order(:area).count.each do |k|
      a2 << { "label" => k[0][0] + " " + t('stamp.statuses.' + k[0][1]), "value" => k[1] }
    end
    a1 << { "key" => "Series1", "values" => a2 }
    @data[2] = a1

    aa1 = []
    aa2 = []
    aa3 = []
    Stamp.all.group(:area).order(:area).where("status ='__not_purchase__'").count.each do |k|
      aa2 << { "label" => k[0], "value" => k[1] }
    end
    Stamp.all.group(:area).order(:area).where("status ='__purchased__'").count.each do |k|
      aa3 << { "label" => k[0], "value" => k[1] }
    end
    aa1 << { "key" => "Not Purchase", "values" => aa2, "color" => "#d67777" }
    aa1 << { "key" => "Purchased", "values" => aa3, "color" => "#77d677" }
    @data[3] = aa1
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stamp
      @stamp = Stamp.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def stamp_params
      params.require(:stamp).permit(:name, :issue_date, :description, :image_path, :remark1, :remark2, :remark3, :group1, :group2, :group3, :price, :area, :status, :leaf_id)
    end
end

myapp/app/helpers/stamps_helper.rb
module StampsHelper

  def stamp_override_defaults(s)
    s.remark1 = t('stamp.override.remark1')
    s.remark2 = t('stamp.override.remark2')
  end

  def stamp_area_selection
    list = []
    Stamp.area_list.each do |area|
        list << [area, area]
    end
    return list
  end

  def stamp_status_selection
    list = []
    Stamp.status_list.each do |s|
        list << [t('stamp.statuses.' + s), s]
    end
    return list
  end

  def stamp_group1_selection
    list = []
    Stamp.group1_list.each do |g|
        list << [g, g]
    end
    return list
  end

  def stamp_leaf_id_selection
    list = []
    list << ['(none)', 0]
    Leaf.all.each do |lf|
        name = lf.group1 + '/' + lf.group2 + '/' + lf.title
        list << [name, lf.id]
    end
    return list
  end

  def stamp_leaf_name(s)
    if s.leaf_id > 0 then
      return name = s.leaf.group1 + '/' + s.leaf.group2 + '/' + s.leaf.title
    else
      return '(none)'
    end
  end

  def stamp_image(i, s)
    if s == Stamp.status_list[1] then
      if i.present? && File.exist?(Stamp.image_path_base + i) then
        return i
      else
        return Stamp.no_image
      end
    else
      return Stamp.not_purchase_image
    end
  end

end

myapp/app/views/stamps/_form.html.erb
<div class="form_layout">

<%= form_for(@stamp) do |f| %>

<%= render :partial => '/parts/form_errors', :locals => {:obj => @stamp} %>

<% stamp_override_defaults(@stamp) if val == t('common.register') %>

<div>
<fieldset>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :area, 'Region' %><br>
  <%= f.select :area, options_for_select(stamp_area_selection, @stamp.area) %><br>
  <%= f.label :group1 %><br>
  <%= f.select :group1, options_for_select(stamp_group1_selection, @stamp.group1) %><br>
  <%= f.label :group2 %><br>
  <%= f.text_field :group2 %><br>
  <%= f.label :group3 %><br>
  <%= f.text_field :group3 %><br>
  <%= f.label :issue_date %><br>
  <%= f.text_field :issue_date %><br>
  <%= f.label :price %><br>
  <%= f.text_field :price %><br>
  <%= f.label :remark1 %><br>
  <%= f.text_field :remark1 %><br>
  <%= f.label :remark2 %><br>
  <%= f.text_field :remark2 %><br>
  <%= f.label :remark3 %><br>
  <%= f.text_field :remark3 %><br>
</fieldset>
</div>

<div>
<fieldset>
  <%= f.label :status %><br>
  <%= f.select :status, options_for_select(stamp_status_selection, @stamp.status) %><br>
  <%= f.label :image_path %><br>
  <%= f.text_field :image_path %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :leaf %><br>
  <%= f.select :leaf_id, options_for_select(stamp_leaf_id_selection, @stamp.leaf_id) %><br>
  <%= f.submit val, {:class => "actions"}%><br>
</fieldset>
</div>

<% end %>

</div>

myapp/app/views/stamps/index.html.erb

<%= render :partial => '/parts/title', :locals => {:val => t('common.stamps')} %>

<div id="operations">
  <%= render :partial => '/parts/paginate', :locals => {:obj => @stamps} %>
  <%= render :partial => '/parts/search', :locals => {:path => stamps_path } %>
  <%= render :partial => '/parts/commands', :locals => {:command => 'index' } %>
</div>

<% if @stamps.present? then %>

<table>
  <thead>
    <tr>
      <th><%= link_to t('stamp.name'), stamps_path(:order => 'name') %></th>
      <th><%= link_to t('stamp.area'), stamps_path(:order => 'area') %></th>
      <th><%= link_to t('stamp.group1'), stamps_path(:order => 'group1') %></th>
      <th><%= link_to t('stamp.group2'), stamps_path(:order => 'group2') %></th>
      <th><%= link_to t('stamp.group3'), stamps_path(:order => 'group3') %></th>
      <th><%= link_to t('stamp.issue_date'), stamps_path(:order => 'issue_date') %></th>
      <th><%= link_to t('stamp.price'), stamps_path(:order => 'price') %></th>
      <th><%= link_to t('stamp.remark1'), stamps_path(:order => 'remark1') %></th>
      <th><%= link_to t('stamp.remark2'), stamps_path(:order => 'remark2') %></th>
      <th><%= link_to t('stamp.remark3'), stamps_path(:order => 'remark3') %></th>
      <th><%= link_to t('stamp.leaf_id'), stamps_path(:order => 'leaf_id') %></th>
      <th><%= link_to t('stamp.status'), stamps_path(:order => 'status') %></th>
      <th><%= t('common.edit') %></th>
    </tr>
  </thead>

  <tbody>
  <% @stamps.each do |stamp| %>
    <tr>
      <td><%= link_to stamp.name, stamp %></td>
      <td><%= stamp.area %></td>
      <td><%= sn(stamp.group1) %></td>
      <td><%= sn(stamp.group2) %></td>
      <td><%= sn(stamp.group3) %></td>
      <td><%= sn(stamp.issue_date) %></td>
      <td><%= sn(stamp.price) %></td>
      <td><%= sn(stamp.remark1) %></td>
      <td><%= sn(stamp.remark2) %></td>
      <td><%= sn(stamp.remark3) %></td>
      <td><%= stamp.leaf_id %></td>
      <td><%= image_tag Stamp.icons[stamp.status] %></td>
      <td><%= link_to image_tag(Stamp.icons['edit']), edit_stamp_path(stamp) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<% else %>

<%= t('message.empty') %>

<% end %>

myapp/app/views/stamps/show.html.erb

<%= render :partial => '/parts/title', :locals => {:val => t('common.show')} %>

<div id="operations">
  <%= render :partial => '/parts/commands', :locals => {:command => 'show', :obj => @stamp } %>
</div>

<div class="form_layout">

<%= form_for(@stamp) do |f| %>

<div>
<fieldset>
  <%= f.label :name, t('stamp.name') %><br>
  <%= f.text_field :name, {:disabled => true} %><br>
  <%= f.label :area, t('stamp.area') %><br>
  <%= f.text_field :area, {:disabled => true} %><br>
  <%= f.label :group1, t('stamp.group1') %><br>
  <%= f.text_field :group1, {:disabled => true} %><br>
  <%= f.label :group2, t('stamp.group2') %><br>
  <%= f.text_field :group2, {:disabled => true} %><br>
  <%= f.label :group3, t('stamp.group3') %><br>
  <%= f.text_field :group3, {:disabled => true} %><br>
  <%= f.label :issue_date, t('stamp.issue_date') %><br>
  <%= f.text_field :issue_date, {:disabled => true} %><br>
  <%= f.label :price, t('stamp.price') %><br>
  <%= f.text_field :price, {:disabled => true} %><br>
  <%= f.label :remark1, t('stamp.remark1') %><br>
  <%= f.text_field :remark1, {:disabled => true} %><br>
  <%= f.label :remark2, t('stamp.remark2') %><br>
  <%= f.text_field :remark2, {:disabled => true} %><br>
  <%= f.label :remark3, t('stamp.remark3') %><br>
  <%= f.text_field :remark3, {:disabled => true} %><br>
</fieldset>
</div>

<div>
<fieldset>
  <%= f.label :status, t('stamp.status') %><br>
  <%= text_field_tag :status, t('stamp.statuses.'+@stamp.status), {:disabled => true} %><br>
  <%= f.label :image_path, t('stamp.image_path') %><br>
  <%= f.text_field :image_path, {:disabled => true} %><br>
  <%= image_tag stamp_image(@stamp.image_path, @stamp.status), :size => Stamp.image_size %><br>
  <%= f.label :description, t('stamp.description') %><br>
  <%= f.text_area :description, {:disabled => true} %><br>
  <%= f.label :leaf, t('stamp.leaf') %><br>
  <%= text_field_tag :leaf, stamp_leaf_name(@stamp), {:disabled => true} %><br>
</fieldset>
</div>

<% end %>

</div>

myapp/app/views/stamps/statistics.html.erb

<%= render :partial => '/parts/title', :locals => {:val => t('common.statistics')} %>

<div style="margin-top:10px;">
  <div id='chart1' class='span4' style="border:solid 1px;height:450px;width:350px;float:left;margin-right:10px;margin-bottom:10px;">
    <svg style='background-color:#fff;height:450px;width:350px'> </svg>
  </div>
  <div id='chart2' class='span4' style="border:solid 1px;height:450px;width:350px;float:left;margin-right:10px;margin-bottom:10px;">
    <svg style='background-color:#fff;height:450px;width:350px'> </svg>
  </div>
  <div id='chart3' style="border:solid 1px;height:450px;width:800px;float:left;margin-bottom:10px;">
    <svg style='background-color:#fff;height:450px;width:800px'> </svg>
  </div>
  <div id='chart4' style="border:solid 1px;height:450px;width:800px;float:left;">
    <svg style='background-color:#fff;height:450px;width:800px'> </svg>
  </div>
</div>

<script>

var chart1 = makePiechart();
var chart2 = makePiechart();

setPieChartAttributes(chart1,"#chart1 svg",statisticsArea());
setPieChartAttributes(chart2,"#chart2 svg",statisticsStatus());

nv.addGraph(chart1);
nv.addGraph(chart2);

var chart3 = makeDiscreteBarChart();

setDiscreteBarChartAttributes(chart3,"#chart3 svg",statisticsAreaStatus());

nv.addGraph(chart3);

var chart4 = makeMultiBarHorizontalChart();

setMultiBarHorizontalChartAttributes(chart4,"#chart4 svg",statisticsAreaStatus2());

nv.addGraph(chart4);

function statisticsArea() {
  return <%= raw @data[0].to_json %>;
}

function statisticsStatus() {
  return <%= raw @data[1].to_json %>;
}

function statisticsAreaStatus() {
  return <%= raw @data[2].to_json %>;
}

function statisticsAreaStatus2() {
  return <%= raw @data[3].to_json %>;
}

</script>