myapp/config/routes.rb
Rails.application.routes.draw do
  resources :virtual_runs
  resources :leafs
  resources :stamps do
    collection do
      get 'statistics'
    end
  end
  resources :modelstocks
  resources :books
  devise_for :users
  resources :groups
  resources :providers
  resources :authors


  root 'authors#index'
  get 'index' => 'authors#index'








end

myapp/app/models/modelstock.rb
#coding: utf-8
class Modelstock < ActiveRecord::Base

  # application id
  APP_ID=2

  # constants
  SCALES = [
    '(none)',
    '1/20', '1/35', '1/72,1/76', '1/144', '1/700', '1/5000'
  ]

  ICONS = {
    'edit' => 'icons/application_edit.png'
  }

  STATUSES = ['__plan__', '__purchase__', '__build__', '__complete__']

  # validation
  validates_presence_of :name, :scale, :status, :group1, :group2, :provider
  validates_length_of :name, :scale, :status, :group1, :group2, :provider, in: 1..255
  validates_inclusion_of :scale, within: SCALES
  validates_inclusion_of :status, within: STATUSES

  def self.scale_list
    SCALES
  end

  def self.icons
    ICONS
  end

  def self.status_list
    STATUSES
  end

end

myapp/app/controllers/modelstocks_controller.rb
class ModelstocksController < ApplicationController
  before_action :set_modelstock, only: [:show, :edit, :update, :destroy]

  # GET /modelstocks
  def index

    # ORDER BY parameter
    if params[:order].present? then
      order = params[:order]
    elsif session[:order].present? then
      order = session[:order]
    else
      order = 'name' # default
    end
    session[:order] = order # store order

    # LIKE parameter
    if params[:keyword].present? && params[:commit].present? && params[:commit]==t('common.search') then
      like = '%' + params[:keyword].to_s + '%'
      session[:keyword] = params[:keyword]
    elsif session[:keyword].present? then
      like = '%' + session[:keyword].to_s + '%'
    else
      like = ''
      session[:keyword] = ''
      session[:order] = ''
    end

    # all clear
    if params[:commit].present? && params[:commit]==t('common.clear') then
      like = ''
      session[:keyword] = ''
      session[:order] = ''
    end

    # exec SELECT
    select = 'id, name, scale, status, group1, group2, provider'
    @modelstocks = Modelstock.select(select)
    if like.present? then
      @modelstocks = @modelstocks.where('(name LIKE ?) OR (group2 LIKE ?) OR (group1 LIKE ?)', like, like, like)
    end
    @modelstocks = @modelstocks.order(order).page(params[:page])

  end

  # GET /modelstocks/1
  def show
  end

  # GET /modelstocks/new
  def new
    @modelstock = Modelstock.new
    render_new
  end

  # GET /modelstocks/1/edit
  def edit
    render_edit
  end

  # POST /modelstocks
  def create
    @modelstock = Modelstock.new(modelstock_params)

    if @modelstock.save
      redirect_to @modelstock, notice: t('message.registered')
    else
      render_new
    end
  end

  # PATCH/PUT /modelstocks/1
  def update
    if @modelstock.update(modelstock_params)
      redirect_to @modelstock, notice: t('message.updated')
    else
      render_edit
    end
  end

  # DELETE /modelstocks/1
  def destroy
    @modelstock.destroy
    redirect_to modelstocks_url, notice: t('message.deleted')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modelstock
      @modelstock = Modelstock.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def modelstock_params
      params.require(:modelstock).permit(:name, :description, :scale, :status, :group1, :group2, :provider)
    end
end

myapp/app/helpers/modelstocks_helper.rb
module ModelstocksHelper

  def modelstock_scale_selection
    list = []
    Modelstock.scale_list.each do |s|
        list << [s, s]
    end
    return list
  end

  def modelstock_status_selection
    list = []
    Modelstock.status_list.each do |s|
        list << [t('modelstock.statuses.' + s), s]
    end
    return list
  end

  def modelstock_provider_selection
    list = []
    Provider.where(app_id: Modelstock::APP_ID).each do |p|
        list << [p.name, p.name]
    end
    return list
  end

end

myapp/app/views/modelstocks/_form.html.erb
<div class="form_layout">

<%= form_for(@modelstock) do |f| %>

<%= render :partial => '/parts/form_errors', :locals => {:obj => @modelstock} %>

<div>
<fieldset>
  <%= f.label :name, t('modelstock.name') %><br>
  <%= f.text_field :name %><br>
  <%= f.label :scale, t('modelstock.scale') %><br>
  <%= f.select :scale, options_for_select(modelstock_scale_selection, @modelstock.scale) %><br>
  <%= f.label :status, t('modelstock.status') %><br>
  <%= f.select :status, options_for_select(modelstock_status_selection, @modelstock.status) %><br>
  <%= f.label :group1, t('modelstock.group1') %><br>
  <%= f.text_field :group1 %><br>
  <%= f.label :group2, t('modelstock.group2') %><br>
  <%= f.text_field :group2 %><br>
</fieldset>
</div>

<div>
<fieldset>
  <%= f.label :provider, t('modelstock.provider') %><br>
  <%= f.select :provider, options_for_select(modelstock_provider_selection, @modelstock.provider) %><br>
  <%= f.label :description, t('modelstock.description') %><br>
  <%= f.text_area :description %><br>
  <%= f.submit val, {:class => "actions"} %>
</fieldset>
</div>

<% end %>

</div>

myapp/app/views/modelstocks/index.html.erb

<%= render :partial => '/parts/title', :locals => {:val => t('common.modelstocks')} %>

<div id="operations">
  <%= render :partial => '/parts/paginate', :locals => {:obj => @modelstocks} %>
  <%= render :partial => '/parts/search', :locals => {:path => modelstocks_path } %>
  <%= render :partial => '/parts/commands', :locals => {:command => 'index' } %>
</div>

<% if @modelstocks.present? then %>

<table>
  <thead>
    <tr>
      <th><%= link_to t('modelstock.name'), modelstocks_path(:order => 'name') %></th>
      <th><%= link_to t('modelstock.scale'), modelstocks_path(:order => 'scale') %></th>
      <th><%= link_to t('modelstock.provider'), modelstocks_path(:order => 'provider') %></th>
      <th><%= link_to t('modelstock.group1'), modelstocks_path(:order => 'group1') %></th>
      <th><%= link_to t('modelstock.group2'), modelstocks_path(:order => 'group2') %></th>
      <th><%= link_to t('modelstock.status'), modelstocks_path(:order => 'status') %></th>
      <th><%= t('common.edit') %></th>
    </tr>
  </thead>

  <tbody>
  <% @modelstocks.each do |modelstock| %>
    <tr>
      <td><%= link_to modelstock.name, modelstock %></td>
      <td><%= sn(modelstock.scale) %></td>
      <td><%= sn(modelstock.provider) %></td>
      <td><%= sn(modelstock.group1) %></td>
      <td><%= sn(modelstock.group2) %></td>
      <td><%= t('modelstock.statuses.' + modelstock.status) %></td>
      <td><%= link_to image_tag(Modelstock.icons['edit']), edit_modelstock_path(modelstock) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<% else %>

<%= t('message.empty') %>

<% end %>

myapp/app/views/modelstocks/show.html.erb
<%= render :partial => '/parts/title', :locals => {:val => t('common.show')} %>

<div id="operations">
  <%= render :partial => '/parts/commands', :locals => {:command => 'show', :obj => @modelstock } %>
</div>

<div class="form_layout">

<%= form_for(@modelstock) do |f| %>

<div>
<fieldset>
  <%= f.label :name, t('modelstock.name') %><br>
  <%= f.text_field :name, {:disabled => true} %><br>
  <%= f.label :scale, t('modelstock.scale') %><br>
  <%= f.text_field :scale, {:disabled => true} %><br>
  <%= f.label :status, t('modelstock.status') %><br>
  <%= text_field_tag :status, t('modelstock.statuses.'+@modelstock.status), {:disabled => true} %><br>
  <%= f.label :group1, t('modelstock.group1') %><br>
  <%= f.text_field :group1, {:disabled => true} %><br>
  <%= f.label :group2, t('modelstock.group2') %><br>
  <%= f.text_field :group2, {:disabled => true} %><br>
</fieldset>
</div>

<div>
<fieldset>
  <%= f.label :provider, t('modelstock.provider') %><br>
  <%= f.text_field :provider, {:disabled => true} %><br>
  <%= f.label :description, t('modelstock.description') %><br>
  <%= f.text_area :description, {:disabled => true} %><br>
</fieldset>
</div>

<% end %>

</div>