myapp/config/routes.rb
Rails.application.routes.draw do
  resources :virtual_runs
  resources :leafs
  resources :stamps do
    collection do
      get 'statistics'
    end
  end
  resources :modelstocks
  resources :books
  devise_for :users
  resources :groups
  resources :providers
  resources :authors


  root 'authors#index'
  get 'index' => 'authors#index'








end

myapp/app/views/parts/_commands.html.erb

<%# params: command, obj %>

<div id="command_buttons">
  <% case command %>
  <% when 'index' then %>
    <%= button_to t('common.new'), {:action => 'new'}, :method => :get %>
  <% when 'show' then %>
    <%= button_to t('common.edit'), {:action => 'edit'}, :method => :get %>
    <%= button_to t('common.delete'), {:action => 'destroy', :id => obj.id}, data: {confirm: t('common.confirm')}, :method => :delete %>
    <%= button_to t('common.back'), {:action => 'index'}, :method => :get %>
  <% else %>
    <%= button_to t('common.back'), {:action => 'index'}, :method => :get %>
  <% end %>
</div>

myapp/app/views/parts/_flash_message.erb

<% if notice.present? || alert.present? then %>

<div id="flash">

<% if notice.present? then %>
  <p id="notice"><%= notice %></p>
<% end %>

<% if alert.present? then %>
  <p id="alert"><%= alert %></p>
<% end %>

</div>

<% end %>

myapp/app/views/parts/_footer.html.erb
<div id="footer">
  <div class="block">
    <p>Copyright &copy;<%= Time.now.year %> T.Arai</p>
  </div>
</div>

myapp/app/views/parts/_form_errors.html.erb

<%# params: obj %>

<% if obj.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(obj.errors.count, "error") %> prohibited this information from being saved:</h2>
  <ul>
  <% obj.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

myapp/app/views/parts/_header.html.erb
<div id="header">
  <h1><a href="/"><%= t('common.main_title')%></a></h1>

<% if user_signed_in? %>
<div id="user-navigation">
  <div><%= link_to t('common.virtual_runs'), virtual_runs_path %></div>
  <div><%= link_to t('common.leafs'), leafs_path %></div>
  <div><%= link_to t('common.stamps'), stamps_path %></div>
  <div><%= link_to t('common.books'), books_path %></div>
  <div><%= link_to t('common.modelstocks'), modelstocks_path %></div>
  <div><%= link_to t('common.authors'), authors_path %></div>
  <div><%= link_to t('common.groups'), groups_path %></div>
  <div><%= link_to t('common.providers'), providers_path %></div>
  <div><%= link_to t('common.stamps')+" "+t('common.statistics'), statistics_stamps_path %></div>
  <div><%= link_to t('common.logout'), destroy_user_session_path, method: :delete %></div>
</div>
<% else %>
<% end %>

</div>

myapp/app/views/parts/_paginate.html.erb

<%# params: obj %>

<div id="paginate">
  <%= paginate obj %>
</div>

myapp/app/views/parts/_search.html.erb

<%# params: path %>

<div id="search_operation">
<%= form_tag path, :method => :get do %>
  <%= text_field_tag :keyword, session[:keyword], {:id => "input_keyword"} %>
  <%= submit_tag t('common.search'), { :class => 'search_button' } %>
  <%= submit_tag t('common.clear'),  { :class => 'search_button' } %>
  <%= hidden_field_tag :order, session[:order] %>
<% end %>
</div>

myapp/app/views/parts/_title.html.erb
<h2 id="title"><%= val %></h2>